#spring.datasource.url=jdbc:postgresql://localhost:5432/Ecommerce
#spring.datasource.username = postgres
#spring.datasource.password= 19374628
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
